before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: krlCoLRnie7jEWyRV6yzLU32MNLTj2+kqqH2MQnzUZsgkRY7ANtaTnHeYE9AIyzy7cUGefo6z/tZOn2tZlXppiwHfH05KpfbJvhH2hepe0sepTDL9BFKjomgkPXO8uotiILH81V8+EXDMmVpV0W+z4m0r1+XAEDhkp/Dz1mtY8dLeVtFRVZbSEPkWHrN5ZX3JcbYjTm8UAjJEagJ+2qW7RV3rtF4C5r8gcfuuQPY2mi70ZpZrGQEKlNTK9L1pW4/BrCa0VAwlq2B433AsEiUeArgksejoxgVrhuK/0rDNKmGO4uqGebuPjrCUg0pEMstKhi1sWxSFaMZnvaViLAOnQOWpG2uphxmT3dCvLKEEmN+Tkze1eiaph810WONdP6UmJZpVDkkdF1WO5JsCjX9dyhnLdVDmT7AcspPenVpUxvxJrn6NG82tIP7n71jDf9rQkH/UoZDSUtsTgLQClvnvaeOFU3y/C5aem1dnfVtLL2SBUc3jtfcn3zN/7LGWnaXts/2auq31hD/YAKnv82iJxSxTiDcNCcChLoAR+0CJ4OHi/38N0fUOsluwF1VNMKXQCyDNayirOETf5oGS5xlVaaeegJxbzJAZrHsCml0s1JnzedoxGwlfOGINeZTFYs5FKc4u/d8AJbqnD/4/HZZxejPmtulODxw7PKqAZCuRXY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
